### ISSUE TITLE
SPDIF and sample rates

### ISSUE THREAD

**Issue by MrSVCD** [dawsonjon/PicoRX#123]
Hi
I had a idea about being able to switch the pwm audio out to SPDIF out. SPDIF can use sample rates of 32k 44.1k and 48k.

What is the sample rate for the pwm out?

I have some cheap sound cards that have toslink in so that is where I got the idea from.

**Comment by dawsonjon** [comment]
The DSP generates audio at about 16kHz, this is then interpolated to 250kHz for the PWM to reduce ripple. A 2x interpolation would get you to 32k quite easily.

**Comment by MrSVCD** [comment]
Thank you for the info.
