### ISSUE TITLE
Loop antenna build questions

### ISSUE THREAD

**Issue by MrSVCD** [dawsonjon/PicoRX#141]
I am looking to build a active loop antenna [https://www.pa1m.nl/simple-active-receive-loop/](https://www.pa1m.nl/simple-active-receive-loop/) and I have some questions:

1. Can I use steel for the loop instead of aluminum?
2. Can I use a FT-50A-43 core instead of a FT37-43? [https://www.electrokit.com/en/ferritkarna-ft-50a-43-7.2mm](https://www.electrokit.com/en/ferritkarna-ft-50a-43-7.2mm)
3. Can I use 9v instead of 12V?

Schematic for those that don't like following links:

![Loop-schematic](https://github.com/user-attachments/assets/9ff919d6-4ce3-4097-a5b4-1a2444f05917)

**Comment by penfold42** [comment]
I'm no expert but some thoughts come to mind:

>     1. Can I use steel for the loop instead of aluminum?
Google doesnt seem too positive on steel. lower conductivity, heavier (and rustier!)

>     2. Can I use a FT-50A-43 core instead of a FT37-43? https://www.electrokit.com/en/ferritkarna-ft-50a-43-7.2mm
You might need to adjust the number of turns if the inductance is critical

>     3. Can I use 9v instead of 12V?
You'll lose some gain and might also have to adjust the bias resistors

**Comment by MrSVCD** [comment]
I found aluminium locally so that is no longer a problem. A hardware store for building had it as part of the tile accessories.

**Comment by MrSVCD** [comment]
I have now made the amplifier and purchased a aluminum strip.
![Stencil](https://github.com/user-attachments/assets/3bfbf7b0-3de2-4840-893b-24fe601efe44)
![Drawn](https://github.com/user-attachments/assets/9321fa23-93d4-4a5d-9420-435775794f5d)
![Glued](https://github.com/user-attachments/assets/6cc990aa-661b-4460-97b0-cd9e6fe927a7)
![Solderd and Mounted](https://github.com/user-attachments/assets/775523c1-19fd-4219-8a0e-bfd2811e35f9)
There is a high possibility that my transformer doesn't work but I wanted to try if it works with cat 6.

**Comment by penfold42** [comment]
The links to images dont work either! :)

**Comment by MrSVCD** [comment]
@penfold42 The latest jpeg encoding tricks in the gnu imp did not work.

**Comment by MrSVCD** [comment]
It works! And it has better reception than my wire antenna.
Pictures of the success will come tomorrow.

**Comment by MrSVCD** [comment]
Pictures as prommised:
![Antenna on tripod](https://github.com/user-attachments/assets/c31f64de-cd86-4c40-bab2-1bcb18a68e6b)
![Power](https://github.com/user-attachments/assets/7fa7eae8-8b7e-49ab-ae31-a2e5bc14ad14)
![Competed amp](https://github.com/user-attachments/assets/3a2be4a2-1ce4-4b0c-8dd6-855e3e579b1b)

Here is a video of me turning the antenna back and forth to show of the directionality of the antenna: [RadioTest-640.webm](https://github.com/user-attachments/assets/a6cc77d9-710a-46ea-b00c-a3165e0f1bd1)

Ps. This is inside a metal clad house, so it is going to be better when I get it outside.

**Comment by dawsonjon** [comment]
Nice, really neat looking antenna, thanks for sharing!

**Comment by penfold42** [comment]
Nice work!
