### ISSUE TITLE
fldigi and PicoRX

### ISSUE THREAD

**Issue by MrSVCD** [dawsonjon/PicoRX#152]
Hi,
I am looking into making a WEAFAX receiver to have running for a bit, because fun.
I have trouble getting fldigi (4.2.06) to comunicate with my PicoRX running the latest stable release (2024-11-21).
Has anyone gotten it to work? and how do I do it?

**Comment by MrSVCD** [comment]
![WeaFax 7880kHz](https://github.com/user-attachments/assets/c16b26cc-4019-488f-ba00-1f7fe6a1110f)
I got it sort of working with digital ducktape.
I still can't get fldigi to talk directly with PicoRX.

**Comment by dawsonjon** [comment]
Cool, looks good. Can you give me any more details about the issue? From the image, I'm guessing that cat control is working with grig, but not fldigi? I haven't tried cat control in Fldigi,  It might be that it's using a cat command that I haven't implemented. Looks like the USB audio is working OK? On a Linux platform?

**Comment by MrSVCD** [comment]
For some reason when I press initialize in fldigi, fldigi freezes for a bit and then unchecks hamlib. I have not found the log yet so I don't have more info.

But receiving weafax works great. 
![364](https://github.com/user-attachments/assets/7299f0bf-d9fe-400e-9ca6-4d27235c25d4)
(The jpeg is quite compressed to fit the gemini BBS file size limit)
