### ISSUE TITLE
Position of the 10u C14 and C15 capacitors

### ISSUE THREAD

**Issue by mryndzionek** [dawsonjon/PicoRX#16]
I noticed that the position of those additional C14 and C15 capacitors in [concept.svg](https://github.com/dawsonjon/PicoRX/blob/master/PCB/concept/concept.svg) is different than what is shown [here](https://101-things.readthedocs.io/en/latest/_images/breadboard_radio_circuit.png). Does it make a difference?

**Comment by dawsonjon** [comment]
Yes, good spot! I don't think it matters, I have built it both ways round and it seems to work just as well either way. It is confusing though, so will try to make the documentation consistent.

**Comment by mryndzionek** [comment]
> was the version in the schematic.

You mean `concept.svg`?

**Comment by dawsonjon** [comment]
Yes.

**Comment by mryndzionek** [comment]
Thanks!
