### ISSUE TITLE
PicoRX Breadboard values and questions.

### ISSUE THREAD

**Issue by MrSVCD** [dawsonjon/PicoRX#36]
I am planing to make a PicoRX-breadboard and I have a couple of questions:

![PicoRX-scan](https://github.com/user-attachments/assets/ac7cbf72-5d64-4163-9f51-b54bc4655092)
Is this the correct values for the color codes?

Is the audio out stage correct? It is different from the schematic.

Can I use fst3253mtcx instead of 74CBTLV3253? [https://www.electrokit.com/en/fst3253mtcx-wtssop-16-dual-1-of-4-multiplexer](https://www.electrokit.com/en/fst3253mtcx-wtssop-16-dual-1-of-4-multiplexer)

**Comment by dawsonjon** [comment]
> Is this the correct values for the color codes?
Yes

> Is the audio out stage correct? It is different from the schematic.
It should work either way round.

> Can I use fst3253mtcx instead of 74CBTLV3253? https://www.electrokit.com/en/fst3253mtcx-wtssop-16-dual-1-of-4-multiplexer
Yes, but its a 5v device so needs to be powered from 5v rather than 3.3v. 

Best of Luck
Jon

**Comment by penfold42** [comment]
There is 1 wire missing from the schematic - the rotary encoder's push button goes to GPIO 5

**Comment by MrSVCD** [comment]
Can I replace 56nF to 68nF?

**Comment by dawsonjon** [comment]
Yes, close enough👍

**Comment by MrSVCD** [comment]
Parts have been ordered, I have a deadline of October 1 so hopefully I can get it built before then. https://arcticradio.net/schedule

**Comment by MrSVCD** [comment]
Progress report on my build.
![MainBoard](https://github.com/user-attachments/assets/6a384038-86f6-4303-ab6f-1c9109521d3c)
![AudioOut](https://github.com/user-attachments/assets/553e2676-c38f-4492-a1cb-d9c0af3cacd6)

**Comment by dawsonjon** [comment]
Nice! 👍

**Comment by MrSVCD** [comment]
What does the buttons do?
Backstory: I am reusing a old slide image viewer as the base for my control panel and my rotary switch push button is quite stiff so the viewer moves around if i mount it on the side.

**Comment by MrSVCD** [comment]
I now have a working radio! It is late here so I will test it more tomorrow.

**Comment by penfold42** [comment]
> What does the buttons do? Backstory: I am reusing a old slide image viewer as the base for my control panel and my rotary switch push button is quite stiff so the viewer moves around if i mount it on the side.

The encoder push button is not (presently) required.
- in the home screen it jumps straight into Recall
- in the menus, doubles as the right (MENU) button

**Comment by MrSVCD** [comment]
![20240914_155402](https://github.com/user-attachments/assets/0a660546-542c-4639-9b57-d839608d5333)
Accidental power supply, did not think it would work.

![20240914_155359](https://github.com/user-attachments/assets/1a2865f4-b801-493e-8b3b-270d72cc808a)
Complete radio.

![20240914_155355](https://github.com/user-attachments/assets/a83c2278-3964-44c7-afdc-7bf179542d86)
So the next goal is to build the radio fully into this viewer since there is quite some space in it.

![20240913_210406](https://github.com/user-attachments/assets/aaab50fa-679b-4ba4-a112-700eaae359bb)
![20240913_210355](https://github.com/user-attachments/assets/4df9fdc2-28fc-4390-b70d-17418ee70aa9)

**Comment by penfold42** [comment]
I love it!

I may have to get some toothpicks, blutak and 3 credit card size fresnel magnifiers....

**Comment by MrSVCD** [comment]
I am now satisfied with my build. I received my first LW station so I very happy.

**Comment by dawsonjon** [comment]
Cool, really pleased you got it working!
