### ISSUE TITLE
Request reprint and translation of your wiki-“Pi Pico Rx - A crystal radio for the digital age?”

### ISSUE THREAD

**Issue by winshao1** [dawsonjon/PicoRX#4]
Hi Jon,
I am a Chinese engineer who has just started work, and feel fortunate to have come across your wiki. This article has ignited my passion for creation,and I want to develop some new hobbies about electronics. Can I translate it into Chinese and sharing it on local platforms?
I will ensure proper attribution by tagging the source and including all original links. If possible, I kindly request your response and look forward to getting your permission!

Best regards,
Hongjie Shao
1472033503@qq.com

**Comment by dawsonjon** [comment]
Hi Hongjie,

Thanks very much for you interest, it's always nice to get feedback like this! I welcome your suggestion to translate and share the wiki. This kind of collaboration is very much in the spirit of the project!

Best of luck with your endeavours.
Best regards
Jon
