### ISSUE TITLE
schematic small error about filter cutoff frequency

### ISSUE THREAD

**Issue by yongfeicao** [dawsonjon/PicoRX#5]
I found  maybe a small mistake on the page 4 of you schematic (pipicorx.pdf), The LPF of IQ signal cutoff frequency should be 60kHz not 59Mhz?

**Comment by dawsonjon** [comment]
Sorry for the delay...
Thanks very much for your comment, you are correct it was a mistake. I have corrected it now!
Thanks
Jon
