### ISSUE TITLE
pico 2 support?

### ISSUE THREAD

**Issue by penfold42** [dawsonjon/PicoRX#8]
and will the boosted core clocks and floating point and DSP instructions help?

**Comment by jumbo5566** [comment]
pico is engught,not recomm pico 2

**Comment by bmentink** [comment]
Yep, request a pico 2 port please, not only is it faster 150Mhz but ADC noise problem is fixed. Any chance?
Also, how do I use the python script to change the memory table for the bands. I guess I need a python serial module?

**Comment by dawsonjon** [comment]
Have added pico2 support. Quite a big performance improvement. There is a
video here: https://youtu.be/QfNhv-COuvU.
There is a crude command line application to upload memory contents from a
.csv file. https://github.com/dawsonjon/PicoRX/tree/master/memory_loader. I
think PySerial is the only dependency. You need to select "USB Memory
Upload" from the menu and then run the script. If there is interest, I
could make a portable GUI app similar to chirp.
