### ISSUE TITLE
Received frequencies 

### ISSUE THREAD

**Issue by assolutooccidentale** [dawsonjon/PicoRX#9]
Hi,
Would the radio be useful in Italy?
FM radio frequencies here should range from 87 to 108 Mhz

**Comment by dawsonjon** [comment]
This project doesn't cover broadcast FM radio. If that's what you need, you could checkout this project https://101-things.readthedocs.io/en/latest/fm_radio.html. It covers 87 to 108MHz out of the box so should work fine in Italy I think.
