### ISSUE TITLE
NE5532P opamp issue

### ISSUE THREAD

**Issue by mryndzionek** [dawsonjon/PicoRX#92]
I've tested NE5532P opamp. It's 10MHz bandwidth and noise density of 5 (at 1kHz), but it doesn't seem to be working. Recommended minimum supply voltage is 5V. I'm powering from USB, which after diode drop is 4.6V. Could this be the issue? Some sources claim that it operates from 3V.

**Comment by dawsonjon** [comment]
I haven't tried it myself, but it's quite a popular option for this type of thing.  You could try a 5v power supply to eliminate the voltage drop as a possibility? Maybe power on Vbus rather than Vsys? What are the symptoms? Is the op-amp saturating or sitting around mid supply rail?

**Comment by mryndzionek** [comment]
> I haven't tried it myself, but it's quite a popular option for this type of thing. You could try a 5v power supply to eliminate the voltage drop as a possibility? Maybe power on Vbus rather than Vsys? What are the symptoms? Is the op-amp saturating or sitting around mid supply rail?

The receiver shows extremely low signal, barely breaking S0 squelch on some frequencies. I also tried LM358P and it works! Just a little bit more noise than MCP6022. I think this is faulty chip. I'll have some more in few days, so I'll check then.

**Comment by kf4mot** [comment]
> I think this is faulty chip. I'll have some more in few days, so I'll check then.

Just curious if you have any follow up on this? Or your like me and half your new parts get stuffed away or buried under a pile :)

**Comment by mryndzionek** [comment]
> > I think this is faulty chip. I'll have some more in few days, so I'll check then.
> 
> Just curious if you have any follow up on this? Or your like me and half your new parts get stuffed away or buried under a pile :)

NE5532 is +/-5, so 10V. That is why it wasn't working (I think). However I found MC33078 from ST (https://www.st.com/en/amplifiers-and-comparators/mc33078.html). It's +/-2.5, cheap and works nicely 😄. Still, if money is not an issue a rail-to-rail opamp would be best.
