### ISSUE TITLE
First weather fax decode !

### ISSUE THREAD

**Issue by mryndzionek** [dawsonjon/PicoRX#93]
Pinneberg at 3855kHz. Not bad for urban environment and indoor DIY YouLoop antenna:
![Pinneberg_3855_1727378846](https://github.com/user-attachments/assets/e406087c-4d21-4f33-8cd7-a834713dd1c2)

**Comment by mryndzionek** [comment]
The pattern of short horizontal lines is due to suspend via timeout.

**Comment by dawsonjon** [comment]
Those are very impressive results! I think it might be worth adding a facility to disable the battery monitor for digital modes, and we could probably reduce the frequency of the updates so that they are less intrusive.

**Comment by mryndzionek** [comment]
> Those are very impressive results! I think it might be worth adding a facility to disable the battery monitor for digital modes, and we could probably reduce the frequency of the updates so that they are less intrusive.

We are suspending just to read the voltage and temp., right? So actually it's not so bad to only have those values updated when the settings change.

**Comment by dawsonjon** [comment]
Yes, agreed. There might be periods when the same station is being to and the battery voltage wouldn't update, but I wouldn't have thought it would be necessary to check more than once every minute or so.
