### ISSUE TITLE
User Manual

### ISSUE THREAD

**Issue by MrSVCD** [dawsonjon/PicoRX#94]
Hej
I just discovered that you can use the left and right buttons to modify the size of the steps in frequency the encoder takes.

Is there any user manual for the radio?

Or is it more that I have mentioned it so it is now my problem?

**Comment by penfold42** [comment]
In the testing branch:
https://github.com/dawsonjon/PicoRX/tree/testing/user_manual

There's been a lot of activity in the Testing branch - 126 commits ahead of Master

**Comment by MrSVCD** [comment]
Nice 👍
Time for me to make a build server, aka a raspberry pi in a corner.
